Fix user listing syntax
Fix the error:
> TypeError: string indices must be integers
Caused by `print "{0}".format("\n".join(i["username"] for i in userlist))`
`userlist` is a dictionary with {account :{dictionary of parameters}} so I use values() to return the dictionary of parameters.